const money=n=>`Rs ${Math.round(n).toLocaleString('en-IN')}`;
const fixed=n=>Number(n.toFixed(4)).toString();
// Additional problem families avoid filling a level with a single numerical.
// Each case supplies its own assumptions; none uses an unstated current rate.
export function extraNumerical(unit,level,i,q){
 if(i<5)return null;
 const v=i%5+1,g=Math.floor(i/5);
 const make=(topic,stem,value,others,explanation)=>q(unit,level,i,topic,stem,value,others,explanation);
 if(level==='hard'){
  if(unit===1){
   const exp=300+v*20,imp=400+v*15,services=40+v*3,primary=-20,secondary=15,ca=exp-imp+services+primary+secondary;
   return make('BOP current-account aggregation',`BOP figures in the same monetary units are: merchandise exports ${exp}, merchandise imports ${imp}, net service receipts ${services}, net primary income -20 and net secondary income +15. A separate foreign equity financing inflow is 60. What is the current-account balance, with surplus positive and deficit negative?`,`${ca}`,[`${exp-imp}`,`${ca+60}`,`${ca-15}`],`Current account=${exp}-${imp}+${services}-20+15=${ca}. The equity financing inflow belongs to the financial account under the stated BOP classification and is not added to current income.`);
  }
  if(unit===2){
   const aq=120+v*5,ap=8+v,sp=10+v,sq=100+v*5,pv=aq*(sp-ap),uv=sp*(sq-aq),total=pv+uv;
   return make('Material variances reconciliation',`For actual output, standard material quantity is ${sq} kg at Rs ${sp}/kg. Actual quantity purchased and used is ${aq} kg at Rs ${ap}/kg. Use favourable variance as positive and adverse as negative. What are price variance, usage variance and total material cost variance?`,`Price ${pv}; usage ${uv}; total ${total}`,[`Price ${sq*(sp-ap)}; usage ${uv}; total ${sq*(sp-ap)+uv}`,`Price ${pv}; usage ${-uv}; total ${pv-uv}`,`Price ${-pv}; usage ${uv}; total ${uv-pv}`],`Price variance=AQ(SP-AP)=${aq}(${sp}-${ap})=${pv}. Usage variance=SP(SQ-AQ)=${sp}(${sq}-${aq})=${uv}. Their sum ${total} equals standard cost ${sq*sp} minus actual cost ${aq*ap}.`);
  }
  if(unit===3){
   const sp=12+v,vc=10+v,fc=200+v*30,units=50+v*10,loss=fc-(sp-vc)*units;
   return make('Competitive operation versus shutdown',`A competitive firm's profit-maximising positive-output candidate is ${units} units at price Rs ${sp}. At that output AVC is Rs ${vc}; fixed cost Rs ${fc} is unavoidable this period. Assume the specified output lies on the appropriate rising MC segment and is the best operating candidate. What is the short-run decision and loss?`,`Operate; loss ${money(loss)}`,[`Shut down; loss ${money(loss)}`,`Operate; loss ${money(fc)}`,`Shut down; loss ${money(fc+(sp-vc)*units)}`],`Operating contribution=(P-AVC)Q=(${sp}-${vc})${units}=${(sp-vc)*units}. Operating loss=FC-contribution=${loss}; shutdown loses the unavoidable FC ${fc}. Positive contribution makes operating the smaller-loss choice on the stated facts.`);
  }
  if(unit===4){
   const sales=1000+v*100,vc=sales*.6,fc=200,interest=50,ebit=sales-vc-fc,ebt=ebit-interest,combined=(sales-vc)/ebt;
   return make('Combined leverage sensitivity',`At current sales ${money(sales)}, variable operating cost is ${money(vc)}, fixed operating cost ${money(fc)} and fixed interest ${money(interest)}. No preference dividend applies. Under the local linear leverage model, by approximately what percentage does EPS change for a 1% sales increase?`,`${fixed(combined)}%`,[`${fixed((sales-vc)/ebit)}%`,`${fixed(ebit/ebt)}%`,`${fixed((sales-vc)/ebit+ebit/ebt)}%`],`Contribution=${sales-vc}, EBIT=${ebit}, EBT=${ebt}. Combined leverage=DOL×DFL=contribution/EBT=${fixed(combined)}. A 1% sales increase therefore gives approximately ${fixed(combined)}% EPS increase around this point.`);
  }
  if(unit===5){
   const r=.3+v*.1,sx=5+v,sy=12+v,forward=r*sy/sx,reverse=r*sx/sy;
   return make('Regression coefficients and determination',`For paired data with positive SD(X)=${sx}, SD(Y)=${sy} and r=${r.toFixed(1)}, which gives b(Y on X), b(X on Y) and R-squared for simple regression with an intercept? Round coefficients to four decimals.`,`Forward ${forward.toFixed(4)}; reverse ${reverse.toFixed(4)}; R² ${(r*r).toFixed(4)}`,[`Forward ${reverse.toFixed(4)}; reverse ${forward.toFixed(4)}; R² ${(r*r).toFixed(4)}`,`Forward ${forward.toFixed(4)}; reverse ${(1/forward).toFixed(4)}; R² ${r.toFixed(4)}`,`Forward ${forward.toFixed(4)}; reverse ${reverse.toFixed(4)}; R² ${r.toFixed(4)}`],`Forward slope=r SD(Y)/SD(X)=${forward.toFixed(4)}. Reverse=r SD(X)/SD(Y)=${reverse.toFixed(4)}. Product equals r²=${(r*r).toFixed(4)}, also R² in this simple-intercept regression setting.`);
  }
  if(unit===8){
   const campaign=60000+v*6000,net=1000+v*100,vc=net*.6,baseline=100,add=Math.ceil(campaign/(net-vc));
   return make('Campaign incremental break-even',`A campaign costs ${money(campaign)}. Each genuinely additional sale has net revenue ${money(net)} and variable fulfilment cost ${money(vc)}. Without the campaign, ${baseline} sales would occur anyway; they have no incremental contribution for this decision. What minimum total sales during the campaign cover its cost? Ignore all other changes.`,`${baseline+add} sales`,[`${add} sales`,`${baseline+Math.ceil(campaign/net)} sales`,`${baseline+add+100} sales`],`Incremental contribution per extra sale=${money(net-vc)}. Additional sales required=ceil(${campaign}/${net-vc})=${add}. Include ${baseline} baseline sales to express the required total: ${baseline+add}.`);
  }
  if(unit===10){
   const salary=400000+v*20000,businessLoss=80000+v*5000,stcg=50000+v*3000,stcl=10000+v*1000,gti=salary+stcg-stcl;
   return make('Historical brought-forward loss and GTI',`Historical 1961 Act, AY 2025–26, old regime: computed salary ${money(salary)}, eligible brought-forward ordinary non-speculation business loss ${money(businessLoss)}, ordinary short-term capital gain ${money(stcg)} and current-year short-term capital loss ${money(stcl)}. No business profit or other income exists. What GTI follows from permitted set-off? Do not apply deductions or compute later carry-forward.`,money(gti),[money(gti-businessLoss),money(salary+stcg),money(gti+businessLoss)],`Current-year STCL offsets the eligible STCG, leaving ${money(stcg-stcl)}. The brought-forward ordinary business loss is restricted to eligible business profits; none exists here. GTI=salary+net capital gain=${money(gti)}. This restriction concerns brought-forward business loss, not the broader set-off available for a current-year ordinary business loss.`);
  }
 }
 if(level!=='extreme')return null;
 if(unit===1){
  if(g===1){
   const tariff=10+v*2,dq=200-v*10,sq=40+v*5,dc=10+v,ds=5+v,imports=dq-sq-dc-ds,rev=tariff*imports,loss=.5*tariff*(dc+ds);
   return make('Small-country tariff welfare',`A small country faces an unchanged world price. A specific tariff Rs ${tariff}/unit raises domestic price by that full amount. Domestic demand falls from ${dq} to ${dq-dc}; domestic supply rises from ${sq} to ${sq+ds}. Demand and supply are linear over this interval; no externality or terms-of-trade effect applies. What are tariff revenue and national deadweight loss?`,`Revenue ${money(rev)}; loss ${money(loss)}`,[`Revenue ${money(tariff*(dq-sq))}; loss ${money(loss)}`,`Revenue ${money(rev)}; loss ${money(tariff*(dc+ds))}`,`Revenue ${money(rev+loss)}; loss ${money(loss)}`],`Post-tariff imports=(${dq}-${dc})-(${sq}+${ds})=${imports}. Revenue=${tariff}×${imports}=${money(rev)}. Consumption and production triangles sum to 0.5×${tariff}×(${dc}+${ds})=${money(loss)}. Revenue is a domestic transfer, not part of deadweight loss.`);
  }
  if(g===2){
   const ad=2+v,ac=6+v,bd=5+v,bc=8+v,oa=ac/ad,ob=bc/bd,t=(oa+ob)/2,qty=20+v*5,ga=(oa-t)*qty,gb=(t-.1-ob)*qty;
   return make('Comparative cost exchange gains and fee',`A needs ${ad} labour hours for X and ${ac} for Y; B needs ${bd} for X and ${bc} for Y. Labour is the only production input. B exports ${qty} Y to A. Gross exchange price is exactly the midpoint between the two countries' opportunity costs of Y in X. A pays that gross price; B incurs an additional transaction cost of 0.1 X per Y exported. Measure gains against each country's own production opportunity cost. What gains in X result? Round final results to four decimals without rounding intermediate values.`,`A gains ${ga.toFixed(4)} X; B gains ${gb.toFixed(4)} X`,[`A gains ${ga.toFixed(4)} X; B gains ${((t-ob)*qty).toFixed(4)} X`,`A gains ${gb.toFixed(4)} X; B gains ${ga.toFixed(4)} X`,`A gains ${(-ga).toFixed(4)} X; B gains ${gb.toFixed(4)} X`],`Opportunity costs of Y: A=${ac}/${ad}, B=${bc}/${bd}; B's is lower. Midpoint price t=(${ac}/${ad}+${bc}/${bd})/2. A gains (${ac}/${ad}-t)×${qty}=${ga.toFixed(4)} X. B's net price is t-0.1, so B gains (t-0.1-${bc}/${bd})×${qty}=${gb.toFixed(4)} X. Both gains are positive on these facts.`);
  }
  const goods=-100-v*10,service=30+v*5,income=-20,transfer=10,ca=goods+service+income+transfer,privateInflow=40+v*2,reserveSale=-(ca+privateInflow);
  return make('Current-account financing reconciliation',`BOP net goods ${goods}, services ${service}, primary income -20 and secondary income +10 use a common unit. Ignore errors and the capital account. Net private financial financing inflow is ${privateInflow}. Use positive reserve sales as financing inflows and assume official reserves supply the entire remaining financing need. What current-account balance and reserve sale satisfy the stated identity?`,`Current account ${ca}; reserve sale ${reserveSale}`,[`Current account ${ca}; reserve sale ${-reserveSale}`,`Current account ${goods}; reserve sale ${-(goods+privateInflow)}`,`Current account ${ca+privateInflow}; reserve sale ${reserveSale}`],`Current account=${goods}+${service}-20+10=${ca}. Under the expressly stated financing-sign convention, CA+private inflow+reserve sale=0. Reserve sale=-(${ca}+${privateInflow})=${reserveSale}; positive means reserves provide financing.`);
 }
 if(unit===2){
  if(g===1){
   const start=100+v*10,done=800+v*20,close=200+v*10,startCost=20000,matCost=100000+v*2000,convStart=10000,convAdded=70000+v*1000,euM=done+close,euC=done+close*.4,rm=(startCost+matCost)/euM,rc=(convStart+convAdded)/euC,closing=close*rm+close*.4*rc;
   return make('Weighted-average process inventory',`Use weighted-average process costing, with no losses. Beginning WIP ${start} units contains material cost ${money(startCost)} and conversion cost ${money(convStart)}. Added costs are materials ${money(matCost)} and conversion ${money(convAdded)}. Completed output is ${done} units; ending WIP ${close} units is 100% material and 40% conversion complete. What is closing WIP cost, nearest rupee?`,money(closing),[money(close*(rm+rc)),money(close*rm),money(closing+convStart)],`Weighted-average equivalent units: materials=${done}+${close}=${euM}; conversion=${done}+0.4(${close})=${euC}. Rates use beginning plus added costs: material=${startCost+matCost}/${euM}; conversion=${convStart+convAdded}/${euC}. Closing cost=${close}×material rate+${close*.4}×conversion rate=${money(closing)}. Beginning completion percentages are not needed under this method.`);
  }
  if(g===2){
   const aC=40+v*2,aH=4,bC=30+v,bH=2,hours=200+v*20,bd=40,remain=hours-bd*bH,aq=remain/aH,total=bd*bC+aq*aC;
   return make('Limiting-factor allocation with demand ceiling',`Product A contributes Rs ${aC}/unit and uses 4 machine hours; B contributes Rs ${bC}/unit and uses 2 hours. Available hours ${hours}; B demand is at most 40 units and A demand is sufficient to use the remainder. Products are divisible; no other relevant difference applies. What production mix maximises total contribution?`,`B=40; A=${aq}; contribution ${money(total)}`,[`A=${hours/aH}; B=0; contribution ${money(hours/aH*aC)}`,`B=${hours/bH}; A=0; contribution ${money(hours/bH*bC)}`,`B=40; A=${remain/bH}; contribution ${money(total)}`],`Contribution/hour: A=${aC}/4=${aC/4}; B=${bC}/2=${bC/2}, so B ranks first. Supply its 40-unit demand using 80 hours. Remaining ${remain} hours make ${aq} A units. Contribution=40(${bC})+${aq}(${aC})=${money(total)}.`);
  }
  const ap=100000+v*10000,abnormal=10000,capital=600000+v*20000,normal=.1,sp=ap-abnormal-capital*normal,gw=sp*3;
  return make('Adjusted super-profit goodwill',`Reported maintainable average profit is ${money(ap)} but includes a non-recurring gain ${money(abnormal)}. Capital employed is ${money(capital)} and normal return 10%. Use three years' purchase of adjusted super profit, with no other adjustment. What goodwill results?`,money(gw),[money((ap-capital*normal)*3),money((ap-abnormal)*3),money(sp)],`Adjusted maintainable profit=${ap}-${abnormal}=${ap-abnormal}. Normal profit=0.10×${capital}=${capital*normal}. Super profit=${sp}; goodwill=3×${sp}=${money(gw)}. The non-recurring gain is removed before comparing with normal profit.`);
 }
 if(unit===3){
  if(g===1){
   const a1=100+v*10,a2=80+v*8,c=20,q1=(a1-c)/2,q2=(a2-c)/4,p1=a1-q1,p2=a2-2*q2;
   return make('Third-degree discrimination optimum',`A monopolist faces separate markets P1=${a1}-Q1 and P2=${a2}-2Q2, no resale, constant MC=20 and no fixed cost. Continuous positive quantities are feasible. Which joint optimum equates both marginal revenues to MC?`,`Q1=${q1}; P1=${p1}; Q2=${q2}; P2=${p2}`,[`Q1=${a1-c}; P1=20; Q2=${(a2-c)/2}; P2=20`,`Q1=${q1}; P1=${p1}; Q2=${q2}; P2=20`,`Q1=${q2}; P1=${p1}; Q2=${q1}; P2=${p2}`],`MR1=${a1}-2Q1=20 gives Q1=${q1}, P1=${p1}. MR2=${a2}-4Q2=20 gives Q2=${q2}, P2=${p2}. Separate demand and no resale allow distinct prices; maximising revenue alone would omit MC.`);
  }
  if(g===2){
   const income=120+v*24,y=income/14,newY=(income+40)/22,newX=2*newY,comp=8*y;
   return make('Complementary-goods compensation and new optimum',`A consumer has U=min(X,2Y), income Rs ${income} and initial prices pX=Rs 4, pY=Rs 6. Price X rises to Rs 8 while price Y stays Rs 6. An actual income grant of Rs 40 is provided. Quantities are divisible. What additional income would preserve the initial utility at the new prices, and what optimal bundle follows from the actual Rs 40 grant? Round final values to four decimals.`,`Required compensation ${fixed(comp)}; new X=${fixed(newX)}, Y=${fixed(newY)}`,[`Required compensation 40; new X=${fixed(newX)}, Y=${fixed(newY)}`,`Required compensation ${fixed(comp)}; new X=${fixed(2*y)}, Y=${fixed(y)}`,`Required compensation ${fixed(4*y)}; new X=${fixed(newX)}, Y=${fixed(newY)}`],`Initial kink X=2Y and budget 4X+6Y=14Y give Y=${income}/14. Preserving that utility after the X price increase requires the same kink bundle, whose extra cost is (8-4)X=8Y=${fixed(comp)}. Actual income is ${income+40}; new budget at the kink is 22Y, giving Y=${fixed(newY)}, X=${fixed(newX)}. Required compensation differs from the actual grant.`);
  }
  const a=100+v*10,b=2,c=20,qr=a/(2*b),qp=(a-c)/(2*b),pr=a-b*qr,pp=a-b*qp,profitR=(pr-c)*qr,profitP=(pp-c)*qp;
  return make('Revenue-maximising versus profit-maximising firm',`Inverse demand is P=${a}-2Q and TC=20Q, with continuous output. Compare the sales-revenue optimum and the profit optimum. Which states their quantities and the extra profit from using the profit optimum?`,`Revenue Q=${qr}; profit Q=${qp}; extra profit=${profitP-profitR}`,[`Revenue Q=${qp}; profit Q=${qr}; extra profit=${profitP-profitR}`,`Revenue Q=${qr}; profit Q=${qr}; extra profit=0`,`Revenue Q=${qr}; profit Q=${qp}; extra profit=${profitP}`],`MR=${a}-4Q. Revenue optimum sets MR=0, Q=${qr}, P=${pr}; profit there=${profitR}. Profit optimum sets MR=20, Q=${qp}, P=${pp}; profit=${profitP}. Improvement=${profitP-profitR}.`);
 }
 if(unit===4){
  if(g===1){
   const usd=10000+v*1000,strike=82,premium=1,spot=78+v,option=usd*(Math.min(strike,spot)+premium),forward=usd*83;
   return make('Currency option versus forward cost',`An Indian importer must buy USD ${usd}. It can buy a dollar call with strike Rs 82/USD and premium Rs 1/USD paid now, or contract a forward at Rs 83/USD. Settlement spot is Rs ${spot}/USD. Ignore time value, charges and counterparty failure. What are total rupee costs under the purchased option strategy and forward?`,`Option ${money(option)}; forward ${money(forward)}`,[`Option ${money(usd*Math.min(strike,spot))}; forward ${money(forward)}`,`Option ${money(usd*(strike+2*premium))}; forward ${money(usd*spot)}`,`Option ${money(option)}; forward ${money(usd*85)}`],`Under the option, buy at min(spot,strike)=${Math.min(spot,strike)} and include paid premium Rs 1: cost=${money(option)}. The forward obliges purchase at 83: cost=${money(forward)}. Unexercised options still cost the premium.`);
  }
  if(g===2){
   const out=100000+v*5000,cf=40000+v*3000,pv=cf*(1/1.1+1/1.1**2+1/1.1**3),npv=pv-out,pi=pv/out;
   return make('NPV and profitability-index reconciliation',`An independent conventional project costs ${money(out)} now and yields ${money(cf)} at each year-end for three years, with no terminal flow. Discount rate 10%. Which gives NPV nearest rupee and profitability index to four decimals, defined as PV of future inflows divided by initial outlay?`,`NPV ${money(npv)}; PI ${pi.toFixed(4)}`,[`NPV ${money(pv)}; PI ${pi.toFixed(4)}`,`NPV ${money(npv)}; PI ${(npv/out).toFixed(4)}`,`NPV ${money(cf*3-out)}; PI ${(cf*3/out).toFixed(4)}`],`PV inflows=${cf}(1/1.1+1/1.21+1/1.331)=${money(pv)}. NPV=PV-${out}=${money(npv)}. PI=PV/${out}=${pi.toFixed(4)}. PI-1 equals NPV/outlay, not PI itself.`);
  }
  const sales=1200000+v*120000,inv=50,rec=40,pay=30,vc=.6,release=vc*sales/360*10;
  return make('Cash-conversion cycle and working-capital release',`Annual credit sales ${money(sales)} use a 360-day year. Inventory days 50, receivable days 40 and payable days 30. For this estimate, both inventory and payable cash values use a constant cost rate 60% of sales; receivables are unchanged. Inventory falls to 40 days. What are the new cash-conversion cycle and estimated inventory cash released?`,`Cycle 50 days; released ${money(release)}`,[`Cycle 60 days; released ${money(release)}`,`Cycle 50 days; released ${money(sales/360*10)}`,`Cycle 120 days; released ${money(release)}`],`New cycle=40+40-30=50 days, down from 60. Ten fewer inventory days release 0.6×annual sales/360×10=${money(release)}. The expressly stated cost basis prevents using sales value for inventory.`);
 }
 if(unit===5){
  if(g===1){
   const n=16+v*4,mean=50+v,s=10,sum=n*mean,sumSq=(n-1)*s*s+n*mean*mean,diff=mean-50,t=diff/(s/Math.sqrt(n)),se=s/Math.sqrt(n),lower=mean-2.1*se,upper=mean+2.1*se;
   return make('Mean inference from raw summary totals',`An independent sample from a normal population has n=${n}, sum of observations ${sum}, and sum of squared observations ${sumSq}. Test null mean 50 and construct a two-sided confidence interval using the supplied t critical magnitude 2.1. Estimate variance with divisor n-1. Which gives the t statistic and confidence interval? Round final values to four decimals.`,`t=${t.toFixed(4)}; interval [${lower.toFixed(4)},${upper.toFixed(4)}]`,[`t=${(diff/s).toFixed(4)}; interval [${lower.toFixed(4)},${upper.toFixed(4)}]`,`t=${t.toFixed(4)}; interval [${(mean-2.1*s).toFixed(4)},${(mean+2.1*s).toFixed(4)}]`,`t=${(-t).toFixed(4)}; interval [${lower.toFixed(4)},${upper.toFixed(4)}]`],`Mean=sum/n=${mean}. Corrected sum of squares=sum(X²)-sum(X)²/n=${(n-1)*100}. Sample variance=corrected sum/(n-1)=100, so s=10 and SE=10/sqrt(${n}). t=(mean-50)/SE=${t.toFixed(4)}. Interval=mean +/-2.1SE=[${lower.toFixed(4)},${upper.toFixed(4)}]. The critical value is supplied for this exercise rather than inferred from an unspecified confidence level.`);
  }
  if(g===2){
   const groups=3+v,total=groups*10,ssb=100+v*20,ssw=200+v*30,dfb=groups-1,dfw=total-groups,f=(ssb/dfb)/(ssw/dfw);
   return make('ANOVA mean squares and F',`A one-way ANOVA has ${groups} independent groups and ${total} observations. Between-groups sum of squares is ${ssb}; within-groups sum is ${ssw}. Which gives the F statistic to four decimals and numerator/denominator degrees of freedom?`,`F=${f.toFixed(4)}; df=${dfb},${dfw}`,[`F=${(ssb/ssw).toFixed(4)}; df=${dfb},${dfw}`,`F=${(1/f).toFixed(4)}; df=${dfw},${dfb}`,`F=${f.toFixed(4)}; df=${groups},${total-1}`],`Between df=k-1=${dfb}; within df=N-k=${dfw}. MSbetween=${ssb}/${dfb}; MSwithin=${ssw}/${dfw}. F=MSbetween/MSwithin=${f.toFixed(4)}. Raw sums-of-squares ratio is not F.`);
  }
  const a=10+v,b=20+v,c=15+v,d=25+v,n=a+b+c+d,row1=a+b,row2=c+d,col1=a+c,col2=b+d,chi=n*(a*d-b*c)**2/(row1*row2*col1*col2);
  return make('Two-by-two chi-square association',`A 2×2 contingency table has first row [${a},${b}] and second row [${c},${d}]. Use Pearson chi-square without continuity correction. Which gives the statistic to four decimals and degrees of freedom? Assume expected counts permit the approximation.`,`Chi-square=${chi.toFixed(4)}; df=1`,[`Chi-square=${(Math.sqrt(chi)).toFixed(4)}; df=1`,`Chi-square=${chi.toFixed(4)}; df=4`,`Chi-square=${(chi*n).toFixed(4)}; df=1`],`Expected counts use row total×column total/N. For this 2×2 table the equivalent formula is N(ad-bc)²/[(a+b)(c+d)(a+c)(b+d)]=${chi.toFixed(4)}. Degrees=(2-1)(2-1)=1. No continuity correction is applied.`);
 }
 if(unit===8){
  if(g===1){
   const volume=1000+v*100,newC=30+v,oldC=40,displaced=200+v*20,promo=10000,profit=volume*newC-displaced*oldC-promo;
   return make('New-product contribution with cannibalisation',`A new item sells ${volume} units contributing Rs ${newC} each before launch promotion. It displaces ${displaced} units of an old item contributing Rs 40 each. Promotion costs Rs 10,000. No other incremental effects occur. What incremental company profit results?`,money(profit),[money(volume*newC-promo),money(volume*newC+displaced*oldC-promo),money((volume-displaced)*newC-promo)],`New contribution=${volume}×${newC}=${volume*newC}. Subtract lost old contribution ${displaced}×40=${displaced*oldC} and promotion 10,000. Incremental profit=${money(profit)}. Cannibalised units lose the old contribution, which need not equal the new contribution.`);
  }
  if(g===2){
   const cost=100+v*20,d1=.2,d2=.1,commission=.1,margin=.25,list=cost/((1-d1)*(1-d2)*(1-commission)*(1-margin));
   return make('Sequential discounts commission and margin',`Unit cost is ${money(cost)}. Customers receive successive discounts 20% and 10% from list price. Dealer commission is 10% of actual post-discount sales revenue. Require profit 25% of receipts remaining after commission, with no other cost. What list price, nearest rupee, meets that stated margin?`,money(list),[money(cost/(.7*.9*.75)),money(cost*1.25/(.8*.9*.9)),money(cost/(.8*.9*.75))],`Discounted revenue=0.8×0.9×list. Receipts after commission=0.9 times that revenue. A 25% margin on these net receipts implies cost=0.75×net receipts. List=${cost}/(0.8×0.9×0.9×0.75)=${money(list)}. Discounts are multiplicative; the margin base is explicitly after commission.`);
  }
  const acquire=100+v*10,annual=80+v*5,r=.1,ret=.8,value=-acquire+ret*annual/(1+r)+ret**2*annual/(1+r)**2;
  return make('Finite-horizon customer value',`Acquisition costs ${money(acquire)} now. A retained customer contributes ${money(annual)} at each of the next two year-ends; probability of retaining from one year to the next is 80%, with no return after attrition. Discount rate 10%. No terminal value or other cost applies. What expected net value, nearest rupee, results?`,money(value),[money(-acquire+annual/1.1+annual/1.21),money(-acquire+.8*annual/1.1+.8*annual/1.21),money(value+acquire)],`Year-1 contribution occurs with probability 0.8; year-2 with 0.8²=0.64. Net value=-${acquire}+0.8(${annual})/1.1+0.64(${annual})/1.21=${money(value)}. Acquisition is paid now and the horizon ends at year 2.`);
 }
 if(unit===10){
  if(g===1){
   const gti=500000+v*40000,deduction=80000,pretax=60000+v*5000,tds=20000,advance=15000,foreign=10000+v*1000,cap=8000+v*500,credit=Math.min(foreign,cap),remaining=pretax-tds-advance-credit;
   return make('Historical total income and prepaid credits',`Historical 1961 Act, AY 2025–26, old regime: computed GTI ${money(gti)} and fully eligible deductions Rs 80,000. Tax before credits is supplied as ${money(pretax)}; do not derive slab tax. Admissible TDS Rs 20,000, advance tax Rs 15,000, and qualifying foreign tax ${money(foreign)} apply. Foreign credit is capped at specified Indian tax ${money(cap)} on the same income. No other adjustment applies. What total income and remaining tax result?`,`Income ${money(gti-deduction)}; tax ${money(remaining)}`,[`Income ${money(gti)}; tax ${money(remaining)}`,`Income ${money(gti-deduction)}; tax ${money(pretax-tds-advance-foreign)}`,`Income ${money(gti-deduction)}; tax ${money(pretax+tds+advance+credit)}`],`Total income=GTI-eligible deductions=${money(gti-deduction)}. Foreign credit=min(${foreign},${cap})=${credit}. Remaining tax=supplied tax-${tds}-${advance}-${credit}=${money(remaining)}. The supplied tax is an assumption rather than a current-rate assertion.`);
  }
  if(g===2){
   const makeCost=100000+v*10000,avoidable=20000,allocated=30000,buy=makeCost+15000,alternative=10000+v*2000,tax=.3,advantage=(makeCost+avoidable+alternative-buy)*(1-tax);
   return make('Corporate make-buy after-tax opportunity cost',`A genuine corporate make-or-buy choice has annual variable make cost ${money(makeCost)}, avoidable fixed make cost Rs 20,000 and unavoidable allocated cost Rs 30,000. Buying costs ${money(buy)} and frees capacity for an alternative earning pretax contribution ${money(alternative)}. Every stated relevant expense deduction and contribution is fully usable at a supplied 30% tax rate; ignore timing and all other differences. What annual after-tax advantage of buying results?`,money(advantage),[money(advantage+allocated*.7),money(advantage-alternative*.7),money(advantage/.7)],`Relevant pretax advantage=avoided variable cost+avoided fixed cost+alternative contribution-buy price=${makeCost}+20000+${alternative}-${buy}=${advantage/.7}. Multiply by 0.7 for the supplied usable tax effects: ${money(advantage)}. Unavoidable allocated cost is unchanged and excluded.`);
  }
  const resale=200000+v*20000,margin=.2,expense=10000+v*1000,price=resale*(1-margin)-expense;
  return make('Transfer pricing resale-price computation',`For an original historical transfer-pricing exercise, use the stipulated resale-price method: uncontrolled resale revenue ${money(resale)}, comparable gross margin 20% of resale revenue, and further permissible adjustment for distributor purchase-related expense ${money(expense)}. No other adjustment applies. What arm's-length purchase price follows from that specified method?`,money(price),[money(resale/(1+margin)-expense),money(resale*(1-margin)+expense),money(resale*margin-expense)],`Deduct comparable gross margin from resale revenue:0.8×${resale}=${resale*.8}. Then deduct the expressly stipulated adjustment ${expense}; price=${money(price)}. The 20% resale margin is not a cost markup and this computation is not TNMM.`);
 }
 return null;
}
