-- Smit Sir Commerce — admissions lead CRM
-- Applied to the connected production Supabase project.

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  mobile text not null,
  mobile_normalized text not null unique,
  class_level integer check (class_level in (11,12) or class_level is null),
  board text check (board in ('CBSE','GSEB','Other') or board is null),
  subjects text[] not null default '{}'::text[],
  study_mode text check (study_mode in ('Online','Offline','Either') or study_mode is null),
  preferred_contact_time text check (preferred_contact_time in ('Morning','Afternoon','Evening','Any time') or preferred_contact_time is null),
  source text not null default 'Direct' check (source in ('Google','Instagram','WhatsApp','Referral','Direct','Other')),
  intent text not null default 'Admission Enquiry' check (intent in ('Free Demo','Admission Enquiry','General Enquiry')),
  message text,
  consent boolean not null default true,
  status text not null default 'New' check (status in ('New','Contacted','Demo Booked','Follow-up','Joined','Lost')),
  owner_notes text,
  next_follow_up timestamptz,
  last_contacted_at timestamptz,
  enquiries_count integer not null default 1 check (enquiries_count >= 1),
  first_path text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  created_at timestamptz not null default now(),
  last_enquiry_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists leads_status_created_idx on public.leads(status, created_at desc);
create index if not exists leads_follow_up_idx on public.leads(next_follow_up) where next_follow_up is not null;
create index if not exists leads_source_created_idx on public.leads(source, created_at desc);
alter table public.leads enable row level security;
drop policy if exists "admins manage leads" on public.leads;
create policy "admins manage leads" on public.leads for all to authenticated
using ((select private.is_platform_admin())) with check ((select private.is_platform_admin()));
revoke all on public.leads from anon, authenticated;
grant select, update on public.leads to authenticated;

create table if not exists public.lead_submissions (
  id bigint generated by default as identity primary key,
  full_name text not null,
  mobile text not null,
  mobile_normalized text,
  class_level integer,
  board text,
  subjects text[] not null default '{}'::text[],
  study_mode text,
  preferred_contact_time text,
  source text not null default 'Direct',
  intent text not null default 'Admission Enquiry',
  message text,
  consent boolean not null default false,
  first_path text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  created_at timestamptz not null default now()
);
alter table public.lead_submissions enable row level security;
drop policy if exists "visitors submit enquiries" on public.lead_submissions;
create policy "visitors submit enquiries" on public.lead_submissions for insert to anon, authenticated
with check (
  consent = true
  and char_length(trim(full_name)) between 2 and 80
  and char_length(regexp_replace(mobile, '\D', '', 'g')) between 10 and 15
  and (class_level in (11,12) or class_level is null)
  and (board in ('CBSE','GSEB','Other') or board is null)
  and subjects <@ array['Accountancy','Economics','Business Studies','Entrepreneurship','Physical Education']::text[]
  and cardinality(subjects) <= 5
  and (study_mode in ('Online','Offline','Either') or study_mode is null)
  and (preferred_contact_time in ('Morning','Afternoon','Evening','Any time') or preferred_contact_time is null)
  and source in ('Google','Instagram','WhatsApp','Referral','Direct','Other')
  and intent in ('Free Demo','Admission Enquiry','General Enquiry')
  and coalesce(char_length(message),0) <= 1000
);
revoke all on public.lead_submissions from anon, authenticated;
grant insert (full_name,mobile,class_level,board,subjects,study_mode,preferred_contact_time,source,intent,message,consent,first_path,utm_source,utm_medium,utm_campaign) on public.lead_submissions to anon, authenticated;
grant usage, select on sequence public.lead_submissions_id_seq to anon, authenticated;

create table if not exists public.lead_activity (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.leads(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists lead_activity_lead_created_idx on public.lead_activity(lead_id, created_at desc);
alter table public.lead_activity enable row level security;
drop policy if exists "admins read lead activity" on public.lead_activity;
create policy "admins read lead activity" on public.lead_activity for select to authenticated using ((select private.is_platform_admin()));
revoke all on public.lead_activity from anon, authenticated;
grant select on public.lead_activity to authenticated;

create or replace function private.prepare_lead_submission()
returns trigger language plpgsql security definer set search_path = public, private as $$
declare normalized text;
begin
  normalized := regexp_replace(coalesce(new.mobile,''), '\D', '', 'g');
  if char_length(normalized) < 10 or char_length(normalized) > 15 then raise exception 'Please enter a valid mobile number'; end if;
  new.full_name := trim(new.full_name);
  new.mobile := trim(new.mobile);
  new.mobile_normalized := normalized;
  new.message := nullif(trim(coalesce(new.message,'')), '');
  new.first_path := nullif(left(trim(coalesce(new.first_path,'')),240), '');
  new.utm_source := nullif(left(trim(coalesce(new.utm_source,'')),120), '');
  new.utm_medium := nullif(left(trim(coalesce(new.utm_medium,'')),120), '');
  new.utm_campaign := nullif(left(trim(coalesce(new.utm_campaign,'')),160), '');
  if exists (select 1 from public.leads l where l.mobile_normalized = normalized and l.last_enquiry_at > now() - interval '90 seconds') then return null; end if;
  return new;
end;
$$;
revoke all on function private.prepare_lead_submission() from public, anon, authenticated;
drop trigger if exists prepare_lead_submission on public.lead_submissions;
create trigger prepare_lead_submission before insert on public.lead_submissions for each row execute function private.prepare_lead_submission();

create or replace function private.process_lead_submission()
returns trigger language plpgsql security definer set search_path = public, private as $$
declare target_id uuid;
begin
  insert into public.leads (full_name,mobile,mobile_normalized,class_level,board,subjects,study_mode,preferred_contact_time,source,intent,message,consent,first_path,utm_source,utm_medium,utm_campaign,created_at,last_enquiry_at,updated_at)
  values (new.full_name,new.mobile,new.mobile_normalized,new.class_level,new.board,new.subjects,new.study_mode,new.preferred_contact_time,new.source,new.intent,new.message,new.consent,new.first_path,new.utm_source,new.utm_medium,new.utm_campaign,new.created_at,new.created_at,new.created_at)
  on conflict (mobile_normalized) do update set
    full_name = excluded.full_name,
    mobile = excluded.mobile,
    class_level = coalesce(excluded.class_level, public.leads.class_level),
    board = coalesce(excluded.board, public.leads.board),
    subjects = case when cardinality(excluded.subjects) > 0 then excluded.subjects else public.leads.subjects end,
    study_mode = coalesce(excluded.study_mode, public.leads.study_mode),
    preferred_contact_time = coalesce(excluded.preferred_contact_time, public.leads.preferred_contact_time),
    source = excluded.source,
    intent = excluded.intent,
    message = coalesce(excluded.message, public.leads.message),
    consent = excluded.consent,
    first_path = coalesce(public.leads.first_path, excluded.first_path),
    utm_source = coalesce(excluded.utm_source, public.leads.utm_source),
    utm_medium = coalesce(excluded.utm_medium, public.leads.utm_medium),
    utm_campaign = coalesce(excluded.utm_campaign, public.leads.utm_campaign),
    status = case when public.leads.status = 'Lost' then 'New' else public.leads.status end,
    enquiries_count = public.leads.enquiries_count + 1,
    last_enquiry_at = excluded.last_enquiry_at,
    updated_at = now()
  returning id into target_id;
  insert into public.lead_activity(lead_id,actor_user_id,event_type,details) values (target_id,null,'enquiry_received',jsonb_build_object('source',new.source,'intent',new.intent));
  return new;
end;
$$;
revoke all on function private.process_lead_submission() from public, anon, authenticated;
drop trigger if exists process_lead_submission on public.lead_submissions;
create trigger process_lead_submission after insert on public.lead_submissions for each row execute function private.process_lead_submission();

create or replace function private.log_lead_owner_change()
returns trigger language plpgsql security definer set search_path = public, private as $$
declare payload jsonb := '{}'::jsonb;
begin
  if old.status is distinct from new.status then payload := payload || jsonb_build_object('old_status',old.status,'new_status',new.status); end if;
  if old.next_follow_up is distinct from new.next_follow_up then payload := payload || jsonb_build_object('next_follow_up',new.next_follow_up); end if;
  if old.owner_notes is distinct from new.owner_notes then payload := payload || jsonb_build_object('notes_updated',true); end if;
  if payload <> '{}'::jsonb then insert into public.lead_activity(lead_id,actor_user_id,event_type,details) values (new.id,auth.uid(),'owner_update',payload); end if;
  new.updated_at := now();
  if old.status is distinct from new.status and new.status in ('Contacted','Demo Booked','Follow-up','Joined') then new.last_contacted_at := now(); end if;
  return new;
end;
$$;
revoke all on function private.log_lead_owner_change() from public, anon, authenticated;
drop trigger if exists log_lead_owner_change on public.leads;
create trigger log_lead_owner_change before update on public.leads for each row execute function private.log_lead_owner_change();
