-- Smit Sir Commerce — secure owner/student access controls
-- Applied to the connected production Supabase project.

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists premium_until timestamptz;

update public.profiles p
set email = u.email,
    updated_at = now()
from auth.users u
where p.id = u.id
  and p.email is distinct from u.email;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, class_level, created_at, updated_at)
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    case when (new.raw_user_meta_data ->> 'class_level') in ('11','12') then (new.raw_user_meta_data ->> 'class_level')::integer else null end,
    now(),
    now()
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    class_level = coalesce(excluded.class_level, public.profiles.class_level),
    updated_at = now();
  return new;
end;
$$;
revoke execute on function public.handle_new_user() from public, anon, authenticated;

drop policy if exists "admins update premium access" on public.profiles;
create policy "admins update premium access"
on public.profiles
for update to authenticated
using ((select private.is_platform_admin()))
with check ((select private.is_platform_admin()));

revoke update on public.profiles from anon, authenticated;
grant update (is_premium, premium_until) on public.profiles to authenticated;

create table if not exists public.premium_access_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  old_is_premium boolean not null default false,
  new_is_premium boolean not null default false,
  old_premium_until timestamptz,
  new_premium_until timestamptz,
  changed_at timestamptz not null default now()
);
create index if not exists premium_access_log_target_changed_idx on public.premium_access_log(target_user_id, changed_at desc);
alter table public.premium_access_log enable row level security;
drop policy if exists "admins read premium access log" on public.premium_access_log;
create policy "admins read premium access log" on public.premium_access_log
for select to authenticated
using ((select private.is_platform_admin()));
revoke insert, update, delete on public.premium_access_log from anon, authenticated;
grant select on public.premium_access_log to authenticated;

create or replace function private.log_premium_access_change()
returns trigger
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if old.is_premium is distinct from new.is_premium
     or old.premium_until is distinct from new.premium_until then
    insert into public.premium_access_log (
      actor_user_id, target_user_id,
      old_is_premium, new_is_premium,
      old_premium_until, new_premium_until
    ) values (
      auth.uid(), new.id,
      old.is_premium, new.is_premium,
      old.premium_until, new.premium_until
    );
  end if;
  return new;
end;
$$;
revoke all on function private.log_premium_access_change() from public, anon, authenticated;

drop trigger if exists premium_access_audit on public.profiles;
create trigger premium_access_audit
after update of is_premium, premium_until on public.profiles
for each row execute function private.log_premium_access_change();
