-- Smit Sir Commerce platform hardening migration
-- Apply in the Supabase SQL editor for the project used by the website.
-- Safe to run more than once where PostgreSQL supports IF NOT EXISTS.

-- 1) Admin role flags on profiles
alter table if exists public.profiles add column if not exists role text default 'student';
alter table if exists public.profiles add column if not exists is_admin boolean default false;

-- Helper: true only for authenticated admin profiles.
create or replace function public.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and (p.is_admin = true or p.role = 'admin')
  );
$$;

-- 2) Cross-device learning state
create table if not exists public.student_learning_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.student_learning_state enable row level security;
drop policy if exists "students read own learning state" on public.student_learning_state;
create policy "students read own learning state" on public.student_learning_state for select to authenticated using (auth.uid() = user_id);
drop policy if exists "students insert own learning state" on public.student_learning_state;
create policy "students insert own learning state" on public.student_learning_state for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "students update own learning state" on public.student_learning_state;
create policy "students update own learning state" on public.student_learning_state for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 3) Test attempts. Existing projects may already have this table.
create table if not exists public.test_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  student_label text,
  test_name text not null,
  subject text,
  score integer not null default 0,
  total_questions integer not null default 0,
  percentage numeric(5,2) not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists test_attempts_user_created_idx on public.test_attempts(user_id, created_at desc);
create index if not exists test_attempts_percentage_idx on public.test_attempts(percentage desc);
alter table public.test_attempts enable row level security;
drop policy if exists "students insert own test attempts" on public.test_attempts;
create policy "students insert own test attempts" on public.test_attempts for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "students read own test attempts" on public.test_attempts;
create policy "students read own test attempts" on public.test_attempts for select to authenticated using (auth.uid() = user_id or public.is_platform_admin());

-- A privacy-preserving leaderboard view can be read by authenticated users without exposing email or profile data.
create or replace view public.test_leaderboard as
select student_label, max(percentage) as percentage, max(created_at) as latest_attempt
from public.test_attempts
where student_label is not null
group by student_label;
grant select on public.test_leaderboard to authenticated;

-- 4) Admin-created learning content such as additional exam tests.
create table if not exists public.content_items (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  type text not null check (type in ('test','announcement','resource')),
  status text not null default 'draft' check (status in ('draft','published','archived')),
  payload jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists content_items_type_status_idx on public.content_items(type, status);
alter table public.content_items enable row level security;
drop policy if exists "public read published content" on public.content_items;
create policy "public read published content" on public.content_items for select to anon, authenticated using (status = 'published' or public.is_platform_admin());
drop policy if exists "admins insert content" on public.content_items;
create policy "admins insert content" on public.content_items for insert to authenticated with check (public.is_platform_admin());
drop policy if exists "admins update content" on public.content_items;
create policy "admins update content" on public.content_items for update to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());
drop policy if exists "admins delete content" on public.content_items;
create policy "admins delete content" on public.content_items for delete to authenticated using (public.is_platform_admin());

-- 5) Product / learning analytics. No emails or free-text answers should be inserted by the app.
create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null check (char_length(event_name) between 1 and 80),
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists learning_events_created_idx on public.learning_events(created_at desc);
create index if not exists learning_events_name_idx on public.learning_events(event_name, created_at desc);
alter table public.learning_events enable row level security;
drop policy if exists "clients insert learning events" on public.learning_events;
create policy "clients insert learning events" on public.learning_events for insert to anon, authenticated with check (user_id is null or user_id = auth.uid());
drop policy if exists "admins read learning events" on public.learning_events;
create policy "admins read learning events" on public.learning_events for select to authenticated using (public.is_platform_admin());

-- Optional: once your own profile is known, set it as admin manually in the SQL editor.
-- Example only; replace the UUID with your authenticated profile id:
-- update public.profiles set role = 'admin', is_admin = true where id = 'YOUR-USER-UUID';
