-- Smit Sir Commerce: test attempt history + anonymised leaderboard
-- Run once in the Supabase SQL editor if the table does not already exist.

create table if not exists public.test_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_label text not null default 'ST',
  test_name text not null,
  subject text not null default 'Commerce',
  score integer not null check (score >= 0),
  total_questions integer not null check (total_questions > 0),
  percentage numeric(5,2) not null check (percentage >= 0 and percentage <= 100),
  created_at timestamptz not null default now()
);

create index if not exists test_attempts_user_created_idx
  on public.test_attempts (user_id, created_at desc);

create index if not exists test_attempts_percentage_idx
  on public.test_attempts (percentage desc);

alter table public.test_attempts enable row level security;

drop policy if exists "students insert own attempts" on public.test_attempts;
create policy "students insert own attempts"
  on public.test_attempts for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "students read leaderboard attempts" on public.test_attempts;
create policy "students read leaderboard attempts"
  on public.test_attempts for select
  to authenticated
  using (true);

-- The leaderboard stores only a short initials-style label, never email addresses.
