import { Link, useLocation } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, CircleHelp, FileQuestion, Sigma } from 'lucide-react';
import SEO from '../components/ui/SEO';
import { growthPageByPath, getGrowthPagesForMaterial, getGrowthStructuredData } from '../data/contentGrowth';

const AR_OPTIONS = {
  A: 'Both Assertion and Reason are true, and Reason correctly explains Assertion.',
  B: 'Both Assertion and Reason are true, but Reason does not correctly explain Assertion.',
  C: 'Assertion is true, but Reason is false.',
  D: 'Assertion is false, but Reason is true.',
};

function NotFound({ pathname }) {
  return <div className="min-h-screen flex items-center justify-center px-4" style={{ background: 'var(--bg-ivory)' }}><SEO title="Practice Page Not Found" description="The requested practice page could not be found." path={pathname} noindex /><div className="card-paper max-w-lg w-full p-8 text-center"><FileQuestion className="w-10 h-10 mx-auto mb-4" style={{ color: 'var(--gold)' }} /><h1 className="text-2xl" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>Practice page not found</h1><Link to="/cbse-practice" className="btn-primary mt-5 inline-flex">Open practice library</Link></div></div>;
}

function McqSection({ page }) {
  return <section className="card-paper p-5 sm:p-8"><h2 className="text-3xl mb-2" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>{page.chapter} MCQs</h2><p className="text-sm mb-6" style={{ color: 'var(--muted)' }}>Original chapter practice. Try each question before opening the answer.</p><div className="space-y-5">{page.mcqs.map((mcq, index) => <article key={`${mcq.question}-${index}`} className="tile-paper p-4 sm:p-5"><h3 className="font-semibold leading-relaxed" style={{ color: 'var(--ink)' }}>Q{index + 1}. {mcq.question}</h3><div className="grid sm:grid-cols-2 gap-2 mt-3">{mcq.options.map((option, i) => <div key={`${option}-${i}`} className="rounded-xl px-3 py-2 text-sm" style={{ background: 'var(--bg-ivory)', color: 'var(--charcoal)' }}>{String.fromCharCode(65 + i)}. {option}</div>)}</div><details className="mt-4"><summary className="cursor-pointer font-semibold text-sm" style={{ color: 'var(--gold)' }}>Show answer & explanation</summary><p className="text-sm leading-relaxed mt-2" style={{ color: 'var(--muted)' }}><strong style={{ color: 'var(--ink)' }}>Answer: {String.fromCharCode(65 + mcq.answer)}.</strong> {mcq.explanation}</p></details></article>)}</div></section>;
}

function ImportantSection({ page }) {
  return <section className="card-paper p-5 sm:p-8"><h2 className="text-3xl mb-2" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>Important questions with answer guidance</h2><p className="text-sm mb-6" style={{ color: 'var(--muted)' }}>Use these as board-style revision prompts. They are original practice questions, not claimed previous-year questions.</p><div className="divide-y" style={{ borderColor: 'var(--border-soft)' }}>{page.questions.map((item, index) => <details key={`${item.question}-${index}`} className="py-4" open={index === 0}><summary className="cursor-pointer font-semibold list-none flex gap-3" style={{ color: 'var(--ink)' }}><span style={{ color: 'var(--gold)' }}>Q{index + 1}</span><span>{item.question}</span></summary><p className="mt-3 leading-7" style={{ color: 'var(--muted)' }}>{item.answer}</p></details>)}</div></section>;
}

function RevisionSection({ page }) {
  return <div className="space-y-6"><section className="card-paper p-5 sm:p-8"><h2 className="text-3xl" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>One-shot recall</h2><div className="grid sm:grid-cols-2 gap-3 mt-6">{page.revision.quickRecall.map((item) => <div key={item} className="tile-paper p-4 text-sm leading-relaxed" style={{ color: 'var(--charcoal)' }}>{item}</div>)}</div></section><section className="card-paper p-5 sm:p-8"><h2 className="text-3xl" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>Exam traps to avoid</h2><div className="space-y-3 mt-5">{page.revision.traps.map((item, index) => <div key={item} className="flex items-start gap-3"><span className="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0" style={{ background: 'var(--gold-bg)', color: 'var(--gold)' }}>{index + 1}</span><p className="leading-7" style={{ color: 'var(--muted)' }}>{item}</p></div>)}</div></section><section className="card-paper p-5 sm:p-8"><h2 className="text-3xl" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>Before you leave this chapter</h2><div className="space-y-3 mt-5">{page.revision.finalCheck.map((item) => <div key={item} className="flex gap-3"><CheckCircle2 className="w-5 h-5 mt-0.5" style={{ color: 'var(--green)' }} /><span style={{ color: 'var(--charcoal)' }}>{item}</span></div>)}</div></section></div>;
}

function AssertionSection({ page }) {
  return <section className="card-paper p-5 sm:p-8"><h2 className="text-3xl" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>Assertion–Reason practice</h2><div className="rounded-xl p-4 mt-5 text-sm" style={{ background: 'var(--gold-bg)', color: 'var(--charcoal)' }}>{Object.entries(AR_OPTIONS).map(([key, value]) => <div key={key}><strong>{key}.</strong> {value}</div>)}</div><div className="space-y-5 mt-6">{page.assertionReason.map((item, index) => <article key={index} className="tile-paper p-5"><p className="leading-7" style={{ color: 'var(--ink)' }}><strong>Assertion:</strong> {item.assertion}</p><p className="leading-7 mt-2" style={{ color: 'var(--charcoal)' }}><strong>Reason:</strong> {item.reason}</p><details className="mt-4"><summary className="cursor-pointer font-semibold text-sm" style={{ color: 'var(--gold)' }}>Show answer</summary><p className="mt-2 text-sm" style={{ color: 'var(--muted)' }}><strong>{item.answer}.</strong> {AR_OPTIONS[item.answer]}</p></details></article>)}</div></section>;
}

function CaseStudySection({ page }) {
  const study = page.caseStudy;
  return <section className="card-paper p-5 sm:p-8"><h2 className="text-3xl" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>Original case study</h2><div className="tile-paper p-5 mt-5 leading-8" style={{ color: 'var(--charcoal)' }}>{study.scenario}</div><div className="space-y-4 mt-6">{study.questions.map((item, index) => <details key={item.question} className="tile-paper p-4" open={index === 0}><summary className="cursor-pointer font-semibold" style={{ color: 'var(--ink)' }}>Q{index + 1}. {item.question}</summary><p className="mt-3 text-sm leading-7" style={{ color: 'var(--muted)' }}>{item.answer}</p></details>)}</div></section>;
}

function NumericalSection({ page }) {
  return <section className="card-paper p-5 sm:p-8"><div className="flex items-center gap-3"><Sigma className="w-7 h-7" style={{ color: 'var(--gold)' }} /><h2 className="text-3xl" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>Worked numericals</h2></div><p className="text-sm mt-3" style={{ color: 'var(--muted)' }}>Try each problem yourself first, then compare your method with the worked steps.</p><div className="space-y-6 mt-6">{page.numericals.map((item, index) => <article key={index} className="tile-paper p-5"><h3 className="font-semibold leading-7" style={{ color: 'var(--ink)' }}>Q{index + 1}. {item.question}</h3><details className="mt-4"><summary className="cursor-pointer font-semibold text-sm" style={{ color: 'var(--gold)' }}>Show solution</summary><ol className="mt-3 space-y-2 text-sm list-decimal pl-5" style={{ color: 'var(--muted)' }}>{item.steps.map((step) => <li key={step}>{step}</li>)}</ol><div className="mt-4 rounded-xl p-3 font-semibold" style={{ background: 'var(--gold-bg)', color: 'var(--ink)' }}>Answer: {item.answer}</div></details></article>)}</div></section>;
}

export default function ContentGrowthPage() {
  const { pathname } = useLocation();
  const page = growthPageByPath[pathname.replace(/\/$/, '')];
  if (!page) return <NotFound pathname={pathname} />;
  const related = getGrowthPagesForMaterial(page.materialId).filter((item) => item.path !== page.path);
  return <div className="min-h-screen" style={{ background: 'var(--bg-ivory)' }}><SEO title={page.title} description={page.description} path={page.path} type="article" publishedTime={page.updated} modifiedTime={page.updated} structuredData={getGrowthStructuredData(page)} /><section className="page-hero"><div className="page-container"><nav className="text-sm flex flex-wrap gap-2 mb-7" style={{ color: 'var(--muted)' }}><Link to="/">Home</Link><span>/</span><Link to="/cbse-practice">CBSE Practice</Link><span>/</span><Link to={page.notesPath}>{page.chapter}</Link><span>/</span><span style={{ color: 'var(--gold)' }}>{page.label}</span></nav><span className="eyebrow">Free · CBSE Class {page.classLevel} · {page.subject}</span><h1 className="mt-5 max-w-4xl">{page.chapter} <em>{page.label}</em></h1><p className="mt-5 max-w-3xl text-lg leading-relaxed" style={{ color: 'var(--muted)' }}>{page.description}</p><div className="flex flex-wrap gap-3 mt-7"><Link to={page.notesPath} className="btn-primary inline-flex items-center gap-2"><BookOpen className="w-4 h-4" /> Read chapter notes</Link><Link to="/cbse-practice" className="btn-secondary inline-flex items-center gap-2">Practice library <ArrowRight className="w-4 h-4" /></Link></div></div></section><main className="page-container section-padding"><div className="grid lg:grid-cols-[minmax(0,1fr)_300px] gap-8 items-start"><div>{page.type === 'mcqs' && <McqSection page={page} />}{page.type === 'important-questions' && <ImportantSection page={page} />}{page.type === 'revision' && <RevisionSection page={page} />}{page.type === 'assertion-reason' && <AssertionSection page={page} />}{page.type === 'case-study' && <CaseStudySection page={page} />}{page.type === 'numericals' && <NumericalSection page={page} />}</div><aside className="space-y-5 lg:sticky lg:top-24"><div className="card-paper p-5"><h2 className="text-xl" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>Practice this chapter</h2><div className="space-y-2 mt-4">{related.map((item) => <Link key={item.path} to={item.path} className="tile-paper p-3 flex items-center justify-between gap-2 text-sm"><span>{item.label}</span><ArrowRight className="w-4 h-4" style={{ color: 'var(--gold)' }} /></Link>)}</div></div><div className="card-paper p-5"><CircleHelp className="w-5 h-5" style={{ color: 'var(--gold)' }} /><h2 className="text-xl mt-3" style={{ fontFamily: 'var(--font-serif)', color: 'var(--ink)' }}>About this practice</h2><p className="text-sm leading-7 mt-2" style={{ color: 'var(--muted)' }}>These are original learning questions prepared for revision. They are not represented as official CBSE questions or previous-year papers.</p></div><Link to={page.notesPath} className="btn-outline-ink w-full inline-flex items-center justify-center gap-2"><ArrowLeft className="w-4 h-4" /> Back to notes</Link></aside></div></main></div>;
}
