import { useState } from 'react';
import { Crown, Play, RotateCcw, X } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { supabase } from '../../lib/supabase';

const q=(question,options,answer,explanation)=>({question,options,answer,explanation});
const extraTests=[
{ id:'money-banking',name:'Money & Banking Test',subject:'Economics',class:12,isFree:true,difficulty:'Medium',questions:[
q('CRR is maintained by commercial banks with:',['RBI','Customers','SEBI','Government'],0,'CRR is the cash reserve commercial banks keep with RBI.'),q('Repo rate is the rate at which:',['Banks lend to RBI','RBI lends to banks','Firms lend to banks','Public lends to RBI'],1,'Repo rate is the policy rate for RBI lending to commercial banks.'),q('An increase in repo rate generally:',['Makes borrowing cheaper','May reduce credit demand','Raises money supply automatically','Eliminates inflation'],1,'Higher borrowing cost can reduce bank credit and demand.'),q('Money used to settle future payments performs:',['Store of value only','Standard of deferred payments','Unit of production','Barter'],1,'Money provides a standard for deferred payments.'),q('Demand deposits are:',['Not money','Part of money supply','Only government debt','Fixed assets'],1,'Demand deposits are commonly included in money supply.'),q('Central bank acts as lender of last resort to:',['Households','Commercial banks','Retailers','Exporters only'],1,'The central bank supports banks facing temporary liquidity problems.'),q('Open market sale of securities by RBI tends to:',['Increase liquidity','Reduce liquidity','Increase exports','Cut taxes'],1,'Selling securities withdraws money from the banking system.'),q('Credit creation depends strongly on:',['Reserve requirements','Weather','Imports only','Population only'],0,'Reserve requirements influence how much banks can expand deposits and credit.') ]},
{ id:'bop-income',name:'BOP & Income Determination Test',subject:'Economics',class:12,isFree:false,difficulty:'Hard',questions:[
q('Exports of services are recorded in:',['Current account','Capital account only','Official reserves only','Government budget'],0,'Services are part of the current account.'),q('Foreign direct investment is generally recorded in:',['Current account','Capital/financial account','Trade balance only','Transfer account'],1,'FDI is a capital/financial flow.'),q('If MPC is 0.8, multiplier equals:',['2','4','5','8'],2,'k=1/(1-MPC)=5.'),q('At equilibrium in a two-sector model:',['S>I','AD=AS','Taxes=exports','Imports=zero'],1,'Income equilibrium occurs where aggregate demand equals aggregate supply.'),q('Autonomous consumption means consumption that:',['Depends fully on income','Exists even at zero income','Equals saving','Is always zero'],1,'It is consumption independent of current income.'),q('Trade deficit means:',['Exports exceed imports','Imports exceed exports','Services are zero','Capital inflow is zero'],1,'A trade deficit occurs when merchandise imports exceed exports.'),q('MPS equals:',['1+MPC','1-MPC','MPC/2','0 always'],1,'MPC + MPS = 1.'),q('A rise in autonomous investment causes equilibrium income to:',['Fall by same amount','Rise by a multiple','Stay fixed','Become zero'],1,'Multiplier effect magnifies the initial investment change.') ]},
{ id:'planning-staffing',name:'Planning & Staffing Test',subject:'Business Studies',class:12,isFree:true,difficulty:'Medium',questions:[
q('Planning begins with:',['Setting objectives','Recruitment','Control','Promotion'],0,'Objectives provide direction to planning.'),q('A policy is:',['A standing guide for decisions','A one-time budget only','A job description','A control report'],0,'Policies guide recurring managerial decisions.'),q('Recruitment means:',['Choosing final candidate','Searching for prospective employees','Training employees','Appraisal'],1,'Recruitment creates a pool of applicants.'),q('Selection is considered:',['Positive process only','Negative process because unsuitable applicants are rejected','No process','Training'],1,'Selection screens and rejects unsuitable candidates.'),q('A budget is generally a:',['Single-use plan','Principle','Policy','Rule only'],0,'Budgets are commonly single-use plans for a specific period/objective.'),q('Training improves:',['Only salary','Skills and job performance','Only seniority','Only recruitment'],1,'Training develops employee capability.'),q('Planning reduces:',['All uncertainty completely','Risk of uncertainty through preparation','Need for goals','Need for coordination'],1,'Planning cannot eliminate uncertainty but helps prepare for it.'),q('Internal recruitment may include:',['Transfer and promotion','Campus placement','Employment exchange','Advertising'],0,'Transfers and promotions are internal sources.') ]},
{ id:'consumer-protection',name:'Consumer Protection Test',subject:'Business Studies',class:12,isFree:false,difficulty:'Medium',questions:[
q('Right to be informed relates to:',['Accurate product information','Free products','Unlimited credit','No bills'],0,'Consumers should receive correct information on quality, price and related details.'),q('ISI mark is commonly associated with:',['Standardisation/certification','Tax payment','Advertising only','Banking'],0,'Certification marks signal conformity with specified standards.'),q('A consumer organisation may:',['Educate and assist consumers','Set repo rate','Issue shares','Collect GST'],0,'Consumer organisations spread awareness and support grievances.'),q('Right to seek redressal means:',['Right to compensation/remedy','Right to free goods','Right to avoid payment','Right to manufacture'],0,'Consumers can seek remedy against unfair practices or defective goods/services.'),q('A misleading advertisement can harm:',['Consumer interest','Only producers','Only banks','None'],0,'Misleading claims can distort consumer choice.'),q('A cash memo is useful because it:',['Provides proof of purchase','Replaces warranty always','Sets MRP','Creates tax policy'],0,'Proof of purchase supports complaints and claims.'),q('Consumer responsibility includes:',['Reading labels and instructions','Ignoring bills','Buying blindly','Avoiding standards'],0,'Informed and careful buying is a consumer responsibility.'),q('Right to choose protects access to:',['A variety of goods/services at competitive prices','Only one seller','No information','Compulsory purchase'],0,'Choice means access to alternatives wherever possible.') ]},
{ id:'demand-elasticity',name:'Demand & Elasticity Test — Class 11',subject:'Economics',class:11,isFree:true,difficulty:'Medium',questions:[
q('Law of demand shows generally:',['Direct price-demand relation','Inverse price-demand relation','No relation','Income relation only'],1,'Other things equal, quantity demanded tends to fall when price rises.'),q('A movement along a demand curve is caused by:',['Change in own price','Income change','Taste change','Population change'],0,'Own-price change causes extension or contraction.'),q('If price falls and total expenditure rises, demand is:',['Elastic','Inelastic','Unit elastic','Perfectly inelastic'],0,'Opposite movement of price and total expenditure implies elastic demand.'),q('A substitute for tea may be:',['Coffee','Sugar only','Cup','Water only'],0,'Coffee can satisfy a similar want and is a substitute.'),q('Normal goods demand generally rises when:',['Income rises','Income falls always','Price rises always','Population becomes zero'],0,'Demand for normal goods tends to increase with income.'),q('Perfectly inelastic demand curve is:',['Horizontal','Vertical','Downward sloping only','Upward sloping'],1,'Quantity remains unchanged despite price change.'),q('Cross elasticity for substitutes is usually:',['Positive','Negative','Zero always','Infinite always'],0,'Price rise of one substitute raises demand for the other.'),q('Opportunity cost is:',['Next best alternative forgone','Money price only','Fixed cost','Sunk cost only'],0,'It is the value of the next best alternative sacrificed.') ]},
{ id:'accounting-basics-11',name:'Accountancy Fundamentals — Class 11',subject:'Accountancy',class:11,isFree:false,difficulty:'Easy',questions:[
q('The accounting equation is:',['Assets = Liabilities + Capital','Assets = Sales + Purchases','Capital = Assets + Liabilities','Profit = Assets'],0,'Assets are financed by liabilities and owner capital.'),q('A business transaction must generally:',['Have financial effect','Be only verbal','Always involve cash','Always create profit'],0,'Accounting records events measurable in money with financial effect.'),q('Capital introduced by owner increases:',['Assets and capital','Liability only','Expense only','Sales only'],0,'Cash/asset rises and owner capital rises.'),q('Purchase of furniture for cash:',['Changes asset composition','Creates revenue','Creates capital','Creates debtor'],0,'Cash falls while furniture rises; total assets may remain unchanged.'),q('Credit sale creates:',['Debtor/receivable','Creditor','Capital loss','Cash immediately'],0,'Customer owes the business, creating a receivable.'),q('Drawings by owner:',['Reduce capital','Increase revenue','Increase liability','Increase profit'],0,'Withdrawals reduce owner equity.'),q('A liability is:',['Present obligation','Owner withdrawal','Revenue','Asset only'],0,'Liability represents a present obligation to outsiders.'),q('Journal is known as:',['Book of original entry','Final account','Ledger balance only','Cash statement'],0,'Transactions are first recorded chronologically in the journal.') ]}
];

function saveLocal(userId,attempt){const k=`ssc-test-attempts-v1:${userId||'guest'}`;let a=[];try{a=JSON.parse(localStorage.getItem(k)||'[]')}catch{};localStorage.setItem(k,JSON.stringify([attempt,...a].slice(0,150)));}

export default function ExtendedTests(){
 const {user,isPremium,displayName}=useAuth(); const [active,setActive]=useState(null); const [answers,setAnswers]=useState([]); const [done,setDone]=useState(false); const [gate,setGate]=useState(false);
 const start=t=>{if(!t.isFree&&!isPremium){setGate(true);return;}setActive(t);setAnswers(Array(t.questions.length).fill(null));setDone(false)};
 const submit=async()=>{if(!active)return;const score=active.questions.reduce((s,item,i)=>s+(answers[i]===item.answer?1:0),0);const pct=Math.round(score/active.questions.length*100);const attempt={id:`${Date.now()}-${active.id}`,testName:active.name,subject:active.subject,score,total:active.questions.length,pct,createdAt:new Date().toISOString()};saveLocal(user?.id,attempt);if(user){await supabase.from('test_attempts').insert({user_id:user.id,student_label:(displayName||'ST').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase(),test_name:active.name,subject:active.subject,score,total_questions:active.questions.length,percentage:pct,created_at:attempt.createdAt});}setDone(true)};
 const score=active?active.questions.reduce((s,item,i)=>s+(answers[i]===item.answer?1:0),0):0;
 return <section className="page-container section-padding"><div className="text-center max-w-2xl mx-auto"><span className="eyebrow">More practice added</span><h2 className="text-3xl sm:text-4xl mt-4" style={{fontFamily:'var(--font-serif)',color:'var(--ink)'}}>6 more focused Commerce tests</h2><p className="mt-3" style={{color:'var(--muted)'}}>Economics, Business Studies and Accountancy across Class 11 and 12.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mt-8">{extraTests.map(t=><article key={t.id} className="card-paper p-5"><div className="flex justify-between gap-3"><div className="text-xs font-semibold" style={{color:'var(--gold)'}}>Class {t.class} · {t.subject}</div>{!t.isFree&&<span className="text-xs font-bold inline-flex items-center gap-1"><Crown className="w-3 h-3"/>PRO</span>}</div><h3 className="text-xl mt-3" style={{fontFamily:'var(--font-serif)',color:'var(--ink)'}}>{t.name}</h3><p className="text-sm mt-2" style={{color:'var(--muted)'}}>{t.questions.length} MCQs · {t.difficulty}</p><button onClick={()=>start(t)} className="btn-primary w-full mt-5 inline-flex justify-center items-center gap-2"><Play className="w-4 h-4"/>Start Test</button></article>)}</div>
 {gate&&<div className="fixed inset-0 z-[160] flex items-center justify-center p-4 bg-black/60"><div className="card-paper max-w-sm w-full p-6 text-center"><Crown className="w-8 h-8 mx-auto" style={{color:'var(--gold)'}}/><h3 className="text-2xl mt-3">Pro test</h3><p className="text-sm mt-2" style={{color:'var(--muted)'}}>This test is included in Pro access.</p><a href="/contact" className="btn-primary block mt-5">Ask for Pro access</a><button onClick={()=>setGate(false)} className="btn-secondary w-full mt-2">Close</button></div></div>}
 {active&&<div className="fixed inset-0 z-[155] overflow-y-auto p-3 sm:p-6 bg-black/70"><div className="card-paper max-w-4xl mx-auto p-5 sm:p-8 relative"><button onClick={()=>setActive(null)} className="absolute right-4 top-4"><X/></button><div className="eyebrow">{done?'Test completed':'Extended test series'}</div><h2 className="text-2xl sm:text-3xl mt-3 pr-10" style={{fontFamily:'var(--font-serif)',color:'var(--ink)'}}>{active.name}</h2>{done?<><div className="text-5xl font-bold mt-7" style={{color:'var(--gold)'}}>{score}/{active.questions.length}</div><div className="space-y-4 mt-7">{active.questions.map((item,i)=><div key={i} className="tile-paper p-4"><div className="font-semibold">{i+1}. {item.question}</div><div className="text-sm mt-2" style={{color:answers[i]===item.answer?'var(--green)':'#B4533C'}}>Your answer: {answers[i]==null?'Not answered':item.options[answers[i]]}</div><div className="text-sm mt-1" style={{color:'var(--muted)'}}>Correct: {item.options[item.answer]} · {item.explanation}</div></div>)}</div><button onClick={()=>{setAnswers(Array(active.questions.length).fill(null));setDone(false)}} className="btn-primary mt-6 inline-flex gap-2"><RotateCcw className="w-4 h-4"/>Retake</button></>:<><div className="space-y-5 mt-7">{active.questions.map((item,i)=><div key={i} className="tile-paper p-4"><div className="font-semibold">{i+1}. {item.question}</div><div className="grid gap-2 mt-3">{item.options.map((o,j)=><button key={j} onClick={()=>setAnswers(a=>a.map((v,k)=>k===i?j:v))} className="text-left rounded-xl px-3 py-2 text-sm" style={{border:'1px solid var(--border)',background:answers[i]===j?'var(--gold-bg)':'var(--bg-white)'}}>{String.fromCharCode(65+j)}. {o}</button>)}</div></div>)}</div><button onClick={submit} className="btn-primary mt-6 w-full">Submit Test</button></>}</div></div>}
 </section>;
}
